spring:
  jmx:
    enabled: true
  application:
    name: test
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:/Java/SpringBootBoard/test/src/main/resources/db/local
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

logging:
  level:
    com:
      sample:
        test: trace

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"