name: OpenShift 
   
env: 
  IMAGE_REGISTRY: ktpocregistry.azurecr.io/test-github-action
  REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  APP_NAME: test-github-action
  IMAGE_TAGS: latest ${{ github.sha }}

  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "my-application"

  APP_PORT: "8080"

on:
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
  push: 
    branches: [ main ]

jobs:
  build-and-push: 
    name: Build and push to github container registry
    runs-on: ubuntu-latest
    environment: ktpoc

    outputs:
        ROUTE: ${{ steps.deploy-and-expose.outputs.route }}
        SELECTOR: ${{ steps.deploy-and-expose.outputs.selector }}

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2

   # https://github.com/redhat-actions/s2i-build#readme
    - name: S2I Build 
      id: build_image
      uses: redhat-actions/s2i-build@v2
      with:
        path_context: '.'
        builder_image: 'registry.access.redhat.com/ubi8/openjdk-21'
        image: ${{ env.APP_NAME }}
        tags: ${{ env.IMAGE_TAGS }}

    # https://github.com/redhat-actions/push-to-registry#readme
    - name: Push to Registry 
      id: push-to-registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}

    # The path the image was pushed to is now stored in ${{ steps.push-to-registry.outputs.registry-path }}

    - name: Add custom host entry to /etc/hosts
      run: |
        IP_ADDRESS_API="20.249.194.222"
        IP_ADDRESS_OAUTH="20.249.169.148"
        HOSTNAME_API="api.test.ocp.kt-poc"
        HOSTNAME_OAUTH="oauth-openshift.apps.test.ocp.kt-poc  console-openshift-console.apps.test.ocp.kt-poc"
        #IP_ADDRESS_API="20.249.175.56"
        #IP_ADDRESS_OAUTH="20.214.214.81"
        #HOSTNAME_API="api.rp.test.az-cloud"
        #HOSTNAME_OAUTH="oauth-openshift.apps.rp.test.az-cloud  console-openshift-console.apps.rp.test.az-cloud"

        # /etc/hosts 파일에 엔트리 추가
        # 'tee -a'는 파일의 끝에 내용을 추가합니다.
        echo "${IP_ADDRESS_API} ${HOSTNAME_API}" | sudo tee -a /etc/hosts > /dev/null
        echo "${IP_ADDRESS_OAUTH} ${HOSTNAME_OAUTH}" | sudo tee -a /etc/hosts > /dev/null
        
        chmod +x ./.github/script.sh


    - name: Install OpenShift CLI
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: 'latest'

    - name: Log in to OpenShift with Username/Password
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
          #openshift_username: ${{ secrets.OPENSHIFT_USERNAME }} 
          #openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }} 
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}

    # Run a script to create a new app or update the current one with the previously pushed container image
    - run: | 
         "${GITHUB_WORKSPACE}/.github/script.sh" ${{ env.APP_NAME }} ${{ env.IMAGE_REGISTRY }}/${{ steps.build_image.outputs.image }}:${{ github.sha }} ${{ env.OPENSHIFT_NAMESPACE }}
